export const searchTypes = {
    QUERY: 'QUERY',
    CLEAR_QUERY: 'CLEAR_QUERY',
    CITY: 'CITY',
    CLEAR_CITY: 'CLEAR_CITY',
    COUNTRY: 'COUNTRY',
    CLEAR_COUNTRY: 'CLEAR_COUNTRY',
    COMPANY: 'COMPANY',
    CLEAR_COMPANY: 'CLEAR_COMPANY',
    RESULTS: 'RESULTS',
    CLEAR_RESULTS: 'CLEAR_RESULTS'
}